- include: usersetup.yml

- name: Add an apt key by id from a keyserver
  apt_key:
    url: http://apt.corollarium.com/archive.key
    state: present

- apt_repository:
    repo: deb [trusted=yes] http://apt.corollarium.com/amd64 /
    state: present

- name: Update APT package cache
  apt: update_cache=yes

- name: Install videowall server packages
  apt:
    pkg: ["videowallserver"]
    state: present

- name: Start at boot by Systemd
  shell: systemctl enable videowallserver.service

- name: restart Systemd
  shell: systemctl daemon-reload

- name: restart Systemd videowall
  shell: systemctl restart videowallserver.service
