- include: usersetup.yml

- name: Add an apt key by id from a keyserver
  apt_key:
    url: http://apt.corollarium.com/archive.key
    state: present

- apt_repository:
    repo: deb [trusted=yes] http://apt.corollarium.com/amd64 /
    state: present

- name: Install videowall server packages
  apt:
    name: videowallserver
    state: latest
    update_cache: yes

- name: Update videowallserver daily
  cron:
    name: "update videowallserver"    
    cron_file: 'videowallserver_daily'
    user: 'root'
    special_time: daily
    job: "/usr/bin/apt -y update && /usr/bin/apt -y install videowallserver"
    state: present

- name: Update videowallserver on reboot
  cron:
    name: "update videowallserver"    
    cron_file: 'videowallserver_reboot'
    user: 'root'
    special_time: reboot
    job: "/usr/bin/apt -y update && /usr/bin/apt -y install videowallserver"
    state: present
  
- name: Start at boot by Systemd
  shell: systemctl enable videowallserver.service

- name: restart Systemd
  shell: systemctl daemon-reload

- name: restart Systemd videowall
  shell: systemctl restart videowallserver.service
