- include: usersetup.yml

- apt_repository:
  repo: deb http://apt.corollarium.com stable main
  state: present

- name: Update APT package cache
  apt: update_cache=yes

- name: Install videowall server packages
  apt:
    pkg: ["videowallserver"]
    state: present

- name: Start at boot by Systemd
  shell: systemctl enable videowallserver.service

- name: restart Systemd
  shell: systemctl daemon-reload

- name: restart Systemd videowall
  shell: systemctl restart videowallserver.service

- monit:
    name: videowallserver
    state: started

