## YAML Template.
---

- name: Set firewall rules
  ufw: rule=allow port={{ item }} proto=tcp
  with_items:
   - '22'
   - '80'
   - '443'
   - '2000'
   - '2001'
   - '2002'

- name: Set firewall rules
  ufw: rule=allow port={{ item }} proto=udp
  with_items:
   - '80'
   - '443'
   - '2000'
   - '2001'
   - '2002'

- name: Allow mosh traffic
  ufw: rule=allow proto=udp port=60000:60020

- name: enable ufw and deny incoming connections by default
  ufw: state=enabled policy=deny direction=incoming

- name: enable ufw and allow outgoing connections by default
  ufw: state=enabled policy=allow direction=outgoing

- name: reload ufw
  ufw: state=reloaded